# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [4]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.randn(7,7)
tensor_A

tensor([[-0.7258,  0.9128, -0.0777, -0.1675,  0.6028, -0.2028, -0.1414],
        [-0.1798,  0.0221,  1.0334,  0.2372, -0.4501,  0.2075, -1.1136],
        [ 0.7970, -1.1101,  0.4701, -0.2264,  1.0582, -0.2551,  1.1755],
        [ 1.0596, -0.5207,  0.1153,  0.7969,  1.5061,  0.1259, -0.3498],
        [ 0.4246,  2.0335,  0.5004, -0.3390,  2.2639,  1.0055, -0.1257],
        [-1.2276, -1.9342,  0.1746, -0.1680,  0.3019, -1.4760, -0.1930],
        [ 0.6594,  2.4300,  0.2581,  1.2476, -0.5574, -1.3205,  2.2028]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
tensor_B = torch.randn(1,7)
tensor_B = tensor_B.transpose(1,0)
# Perform matrix multiplication

torch.multi = tensor_A *tensor_B
torch.multi

tensor([[-0.4521,  0.5686, -0.0484, -0.1043,  0.3755, -0.1263, -0.0881],
        [ 0.2288, -0.0281, -1.3152, -0.3019,  0.5728, -0.2640,  1.4172],
        [-2.1449,  2.9876, -1.2651,  0.6093, -2.8480,  0.6867, -3.1637],
        [-0.0787,  0.0387, -0.0086, -0.0592, -0.1118, -0.0093,  0.0260],
        [ 0.6156,  2.9478,  0.7254, -0.4914,  3.2818,  1.4576, -0.1822],
        [ 1.2281,  1.9349, -0.1747,  0.1681, -0.3020,  1.4765,  0.1931],
        [ 0.3946,  1.4541,  0.1544,  0.7465, -0.3336, -0.7902,  1.3181]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [44]:
seed = 1
torch.manual_seed(seed)
# Create two random tensors
a = torch.randn(7,1)
b = torch.randn(7,1)
# Matrix multiply tensors
mul = a*b
print(mul,mul.shape)



tensor([[ 0.2524],
        [-0.2743],
        [-0.0347],
        [-0.5544],
        [ 0.0263],
        [ 0.0325],
        [ 1.4704]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
seed = 30
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)

a = torch.randn(1,2)
a

tensor([[0.4705, 1.6563]])


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
seed = 1234
torch.manual_seed(seed)


# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"device - {device}")

# Create two random tensors on GPU
a = torch.randn(2,3).to(device)
b = torch.randn(2,3).to(device)
print(a)
print(b)

device - cuda
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]], device='cuda:0')
tensor([[ 0.2310,  0.6931, -0.2669],
        [ 2.1785,  0.1021, -0.2590]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [32]:
# Perform matmul on tensor_A and tensor_B
b_ = torch.transpose(a,0,1)
mul = torch.matmul(a,b_)
print(mul,mul.shape)


tensor([[ 1.1872, -0.7458],
        [-0.7458,  0.6755]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [33]:
# Find max
max = torch.max(mul)
# Find min
min = torch.min(mul)
print(f"max = {max}, min = {min}")

max = 1.1872471570968628, min = -0.7457990646362305


### 9. Find the maximum and minimum index values of the output of 7.

In [34]:
# Find arg max
max = torch.argmax(mul)

# Find arg min
min = torch.argmin(mul)
print(f"max = {max}, min = {min}")



max = 0, min = 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
# Set seed
seed = 1
torch.manual_seed(seed)


# Create random tensor
a = torch.randn(1,1,1,10)


# Remove single dimensions
a_new = torch.randn(10)


# Print out tensors and their shapes
print(a,a.shape)
print(a_new, a_new.shape)


tensor([[[[ 0.6614,  0.2669,  0.0617,  0.6213, -0.4519, -0.1661, -1.5228,
            0.3817, -1.0276, -0.5631]]]]) torch.Size([1, 1, 1, 10])
tensor([-0.8923, -0.0583, -0.1955, -0.9656,  0.4224,  0.2673, -0.4212, -0.5107,
        -1.5727, -0.1232]) torch.Size([10])
