<a href="https://colab.research.google.com/github/masterismail/PyTorch-Fundamentals/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00.PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


## Introduction to tensors
### creating tensors
PyTorch tensors are creates using torch.tensor() 
 

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as python integer
scalar.item() 

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [4,6,10]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 4,  6, 10]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[1]

IndexError: ignored

In [ ]:
TENSOR[0]

### Random tensors

why random tensors?

Random tensors are important because the way many neural networls learn is that they start with tensors full of random numbers and then adjust  those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

In [ ]:
random_tensor.ndim


In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # heigth , width , colour channel (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim 

In [ ]:
  # create a tensor of all zeroes
  zeros = torch.zeros(size=(3,4))
  zeros

In [ ]:
# create a tensor for ones
ones = torch.ones(size=(3,4))
ones

In [ ]:
#finding data type
 ones.dtype

## Creating a range of tensors and tensors-like


In [ ]:
# use torch.range()
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

In [ ]:
torch.__version__

In [ ]:
 #creating alike
 ten_zeros = torch.zeros_like(input=one_to_ten)
 ten_zeros

In [ ]:
#practising range
one_to_five = torch.arange(start = 1, end = 6, step=1)
one_to_five


In [ ]:
 tensor_zeroes=torch.zeros_like(input=one_to_five)
 tensor_zeroes
 

### Tensors data types
**Note:** Tensor datatypes is one of the 3 big errors that you will run into with PyTorch and deep learning: 
1. Tensors are not right data type
2. Tensors are not right shape
3. Tensors are not on the righr device 

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science) 

* Note : In PyTorch the `size` and `shape` means the same thing 

In [ ]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,5.0],
                               dtype=torch.float16,   #what datatype is tensor (float32 or float16)
                               device=None,       # what device is the tensor on 
                               requires_grad=False) #whether or not to track gradient with the tensor 
float_32_tensor

In [ ]:
float_32_tensor.dtype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor  

In [ ]:
float_16_tensor * float_32_tensor

In [ ]:
 int_32_tensor = torch.tensor([3,5,6], dtype=torch.int32)
 int_32_tensor

### getting information from tensors
1.Tensors are not right data type - to do get dataype from a tensor can use `tensor.dtype`

2.Tensors are not right shape -  to do get shape from a tensor can use `tensor.shape`

3.Tensors are not on the righr device - to get device from a tensor can use `tensor.device`


In [ ]:
 #create a tensor
 some_tensor = torch.rand(3,4)
 some_tensor

In [ ]:
# find details about some tesor
print(f"Data type of tensor is: {some_tensor.dtype}")
print(f"Shape of tensor is: {some_tensor.shape}")
print(f"Device of tensor is: {some_tensor.device}")

  ### Manipulating Tensor (Tensors operations)

Tensors operations include :

* Addition

* Subtraction

* Multiplication (element-wise)

* Division

* Matrix multiplication


In [ ]:
# create a tensor and add 11
tensor= torch.tensor([1,2,3])
tensor + 11

tensor([12, 13, 14])

In [ ]:
# multiply a tensor by 10
tensor = torch.tensor([2,3,4])
tensor*10

tensor([20, 30, 40])

In [ ]:
 tensor

tensor([2, 3, 4])

In [ ]:
# subtract tensor
tensor - 10

tensor([-8, -7, -6])

In [ ]:
# try out PyTorch in-built functions
tensor
torch.mul(tensor,10)

tensor([20, 30, 40])

### Matrix Multiplication

There are two main ways to perform multiplication in neural networls and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

more information on this: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(4,5) @ (5,7)` will work
2. The resulting matrix has the shape of the ***outer dimension***
* `(2,3) @ (3,2)` -> `(2,2)`
* `(4,5) @ (5,7)` -> `(4,7)`  


In [ ]:
#example of matrix multiplication when the inner dimensions are same

torch.matmul(torch.rand(3,2),torch.rand(2,3))


tensor([[0.5162, 0.6705, 0.5658],
        [0.8470, 1.1962, 0.9974],
        [0.8628, 1.0130, 0.8684]])

In [ ]:
# element-wise multiplication
print(tensor, "*", tensor)
print(f"equals: {tensor*tensor}")

tensor([2, 3, 4]) * tensor([2, 3, 4])
equals: tensor([ 4,  9, 16])


In [ ]:
 # matrix multiplication (note that "mat" stands for "matrix") 
 %%time
 torch.matmul(tensor,tensor)

CPU times: user 387 µs, sys: 0 ns, total: 387 µs
Wall time: 2.39 ms


tensor(29)

In [ ]:
 %%time
 value =0 
 for i in range(len(tensor)):
   value+= tensor[i] * tensor[i]
print(value)      

tensor(29)
CPU times: user 1.76 ms, sys: 0 ns, total: 1.76 ms
Wall time: 2.21 ms


### One of the most common errors in deep learning : shape errors 


In [ ]:
# shapes for matrix multiplication 
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [3,2]])
# torch.mm(tensor_A , tensor_b) # torch.mm is same as torch.mathmul
torch.matmul(tensor_A,tensor_B)    

RuntimeError: ignored

To fix the tensor shape issues, we can manipulate the shape of one of out tensors using **transpose**

A **transpose** switches the axes or dimesnion of the given tensor

In [ ]:
tensor_B.T

tensor([[ 7,  8,  3],
        [10, 11,  2]])

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 3,  2]])

In [ ]:
# so when we transpose the matrix and multiply we don't get errors
print(f"original shape : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"new shapes : tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"multiplying : {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match") 
output = torch.matmul(tensor_A,tensor_B.T)
print(f"output : {output}")
print(f"\n Output Shape : {output.shape}")

original shape : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
new shapes : tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
multiplying : torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
output : tensor([[ 27,  30,   7],
        [ 61,  68,  17],
        [ 95, 106,  27]])

 Output Shape : torch.Size([3, 3])


# find the mean max, sum, etc(tensor aggregation)

 

In [ ]:
# create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max

x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
# find the mean 
x=x.type(torch.float32)
x.mean()
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
#find the sum
torch.sum(x)
x.sum()

tensor(450.)

In [ ]:
# find the positionn in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimun value occurs

x.argmin()

tensor(0)

In [ ]:
# to find the index of the maximum value
x.argmax()

tensor(9)

## reshaping, stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape 

* view - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor 

* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* Squeeze - removes all `1` dimensions from a tensor 

* Unsqueeze - add a `1` dimension to a targer tensor 

* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [ ]:
#let's create a tensor 
import torch
x=torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extrea dimension 
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view 
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x (because a view of a tensor share ths same memory as the original input)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors of top of each other 
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
 # torch.squeeze() - removes all single dimensions from a target tensor 
print(f"Previous tensor {x_reshaped}")
print(f"Previous Shape {x_reshaped.shape} \n")

#Remove extra dimension from the tensor
x_squeezed = x_reshaped.squeeze()
print(f"New tensor {x_reshaped.squeeze()}")
print(f"Nrevious tensor {x_reshaped.squeeze().shape}")

Previous tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape torch.Size([1, 9]) 

New tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Nrevious tensor torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
 # torch.unsqueeze() - adds a single dimension to a tagrget tensor at a specific dim  
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

#addd an extra dimension with unsqueeze
x_unsqueezed = x_unsqueezed.unsqueeze(dim=1)
print(f" \n New :{x_unsqueezed}")
print(f"New Shape:{x_unsqueezed.shape}")

Previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])
 
 New :tensor([[[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]]])
New Shape:torch.Size([1, 1, 1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor inn a specified order
x_original  = torch.rand(size=(224,224,3)) # [height,width , color_channels]

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis o->1, 1->2 , 2->0
print(f"Previous shape : {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height , width]


Previous shape : torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [19]:
 # create a tensor 
 import torch
 x = torch.arange(1,10).reshape(1,3,3)
 x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [20]:
# Let's index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
# Let's index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [22]:
# Let's index on the most inner brack (last dimension)
x[0][2][2]

tensor(9)

In [23]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [24]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimensiton 
x[:,:, 1]

tensor([[2, 5, 8]])

In [25]:
# get all values of 0 dimenssion but only the 1 index value of 1st and 2nd dimension 
x[:,1,1]

tensor([5])

In [26]:
# get index of 0th and 1st dimension and all values of 2nd dimension 
x[0,0,:]

tensor([1, 2, 3])

In [27]:
# index on x to return 9
x[0,2,2] 


tensor(9)

In [28]:
 x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

and because of this, PyTorch has functionality to interact with it.

* Data is NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [34]:
# NumPy array to tensor 
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)    # warning : when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specifies otherwise.
array , tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [36]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array

array([3., 4., 5., 6., 7., 8., 9.])

In [38]:
 # Tensor to NumPy array 
 tensor = torch.ones(7)
 numpy_tensor = tensor.numpy()
 tensor = torch.ones(8)
 tensor , numpy_tensor  

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

#### in short how a neural network learns

`start with random numbers -> tensors operations -> update random numbers to try and make them of the data -> again -> again -> again - > again...`

to reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [42]:
import torch

#create two random tensors 
random_tensor_A = torch.rand(3,4)
random_tensor_B =  torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5300, 0.2480, 0.2567, 0.8483],
        [0.2586, 0.0830, 0.0205, 0.6677],
        [0.5822, 0.8043, 0.3572, 0.8104]])
tensor([[0.3832, 0.3097, 0.4547, 0.5859],
        [0.0913, 0.0063, 0.1988, 0.5853],
        [0.7298, 0.7384, 0.7547, 0.1398]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
